version: "2.4"
services:
  test-mysql:
    image: mysql:8.0
    container_name: fitness-test-mysql
    volumes:
      - "./volumes/mysql:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    networks:
      - fitness-network
    environment:
      - MYSQL_DATABASE=fitness
      - MYSQL_ROOT_PASSWORD=aaaa8027
      - MYSQL_USER=henry
      - MYSQL_PASSWORD=aaaa8027
  redis:
      image: redis:7.0.1
      ports:
        - "6379:6379"
      networks:
        - fitness-network
      container_name: fitness-redis
networks:
  fitness-network:
    driver: bridge