CREATE TABLE IF NOT EXISTS trainers (
    `user_id` INT(11) UNSIGNED PRIMARY KEY,
    `name` VARCHAR(20) NOT NULL DEFAULT '',
    `nickname` VARCHAR(20) NOT NULL UNIQUE DEFAULT '',
    `trainer_status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
    `email` VARCHAR(50) NOT NULL DEFAULT '',
    `phone` VARCHAR(10) NOT NULL UNIQUE DEFAULT '',
    `address` VARCHAR(50) NOT NULL DEFAULT '',
    `intro` VARCHAR(50) NOT NULL DEFAULT '',
    `create_at` DATETIME NOT NULL DEFAULT NOW(),
    `update_at` DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_trainers_users FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;