CREATE TABLE IF NOT EXISTS admins (
    `id` INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `email` VARCHAR(50) UNIQUE NOT NULL DEFAULT '',
    `password` VARCHAR(16) NOT NULL DEFAULT '',
    `nickname` VARCHAR(32) UNIQUE NOT NULL DEFAULT '',
    `lv` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
    `create_at` DATETIME NOT NULL DEFAULT NOW(),
    `update_at` DATETIME NOT NULL DEFAULT NOW(),
    `last_login` DATETIME NOT NULL DEFAULT NOW(),
    `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT = 1;