CREATE TABLE IF NOT EXISTS certificates (
    `id` INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '證照id',
    `user_id` INT(11) UNSIGNED NOT NULL COMMENT '用戶id',
    `name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '證照名稱',
    `image` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '證照照片',
    `create_at` DATETIME NOT NULL DEFAULT NOW() COMMENT '創建日期',
    `update_at` DATETIME NOT NULL DEFAULT NOW() COMMENT '更新日期',
    CONSTRAINT fk_certificate_user_id_to_users_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT = 1;