CREATE TABLE IF NOT EXISTS user_promote_monthly_statistics (
    `id`        INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '報表id',
    `year`      INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '年份',
    `month`     INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '月份',
    `total`     INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '當月總晉升教練人數',
    `male`      INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '男性晉升教練人數',
    `female`    INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '女性晉升教練人數',
    `exp_1_3`    INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '1-3年經驗晉升教練人數',
    `exp_4_6`    INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '4-6年經驗晉升教練人數',
    `exp_7_10`    INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '7-10年經驗晉升教練人數',
    `exp_11_15`    INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '11-15年經驗晉升教練人數',
    `exp_16_19`    INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '16-19年經驗晉升教練人數',
    `exp_20_up`    INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '20+年經驗晉升教練人數',
    `age_13_17` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '13-17歲晉升教練人數',
    `age_18_24` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '18-24歲晉升教練人數',
    `age_25_34` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '25-34歲晉升教練人數',
    `age_35_44` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '35-44歲晉升教練人數',
    `age_45_54` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '45-54歲晉升教練人數',
    `age_55_64` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '55-64歲晉升教練人數',
    `age_65_up` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '65+歲晉升教練人數',
    `create_at` DATETIME NOT NULL DEFAULT NOW() COMMENT '創建日期',
    `update_at` DATETIME NOT NULL DEFAULT NOW() COMMENT '更新日期',
    UNIQUE KEY `unique_user_promote_monthly_statistics` (`year`, `month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT = 1;