Server:
    RunMode: debug
    HttpPort: 9090
    ReadTimeout: 60
    WriteTimeout: 60
App:
    Debug:
      Version: 2.0.30
    Release:
      Version: 2.0.30
    Production:
      Version: 2.0.30
Resource:
    RootPath: ./volumes/storage
Upload:
    UploadImageMaxSize: 5 #MB
    UploadAudioMaxSize: 10 #MB
    UploadVideoMaxSize: 150 #MB
    UploadImageAllowExt:
      - .jpg
      - .png
      - .jpeg
      - .JPG
      - .PNG
      - .JPEG
    UploadAudioAllowExt:
      - .mp3
    UploadVideoAllowExt:
      - .mp4
Log:
    FileName: fitness
    FileExt: log
    Debug:
      Path: ./volumes/log
      MaxAge: 60 # Minute
      RotationTime: 1 # Minute
    Release:
      Path: ./volumes/log
      MaxAge: 7 # Day
      RotationTime: 1 # Day
    Production:
      Path: ./volumes/log
      MaxAge: 7 # Day
      RotationTime: 1 # Day
Database:
    DBType: mysql
    Debug:
      Host: 127.0.0.1:3306
      DBName: fitness
      UserName: henry
      Password: aaaa8027
    Release:
      Host: fitness-mysql-primary:3306 # k8s svc dns + k8s internal port
      DBName: fitness
      UserName: henry
      Password: aaaa8027
    Production:
      Host: 35.189.179.168:3306 # google cloud sql
      DBName: fitness
      UserName: henry
      Password: aaaa8027
Redis:
    Debug:
      Host: 127.0.0.1:6379
      Password: ""
    Release:
      Host: fitness-redis-master:6379
      Password: aaaa8027
    Production:
      Host: fitness-redis-master:6379
      Password: aaaa8027
JWT:
    Secret: mi
    Issuer: fitness
    Expire: 3600 # Minute
IAP:
    Sandbox: https://sandbox.itunes.apple.com/verifyReceipt
    Product: https://buy.itunes.apple.com/verifyReceipt
    Debug:
      AppStoreServer: https://api.storekit-sandbox.itunes.apple.com
      Password: b3e50e11316943969754106ed24c6a3a # App 專用共享密鑰-用於驗證收據 (App Store Connect -> App 內購買項目 -> App 專用共享密鑰)
      Issuer: 69a6de92-1fe6-47e3-e053-5b8c7c11a4d1 # 發行者-用於產生查詢訂閱API Token (使用者與存取權限 -> App Store Connect API 頁面)
      KeyID: Q2N9VXCN4F # 密鑰id-用於產生查詢訂閱API Token (使用者與存取權限 -> App 內購買項目)
      KeyPath: ./config/SubscriptionKey_Q2N9VXCN4F.p8 # 密鑰-用於產生查詢訂閱API Token
      KeyName: SubscriptionKey_Q2N9VXCN4F.p8 # 密鑰-用於產生查詢訂閱API Token
      BundleID: com.henry.PurchaseDemo
    Release:
      AppStoreServer: https://api.storekit-sandbox.itunes.apple.com
      Password: edea7e33a9974058bcfddad35456f2a0
      Issuer: 18f6ec13-f472-4dbc-8620-9a790c5d48e2
      KeyID: Q7648PT9MF
      KeyPath: ./config/SubscriptionKey_Q7648PT9MF.p8
      KeyName: SubscriptionKey_Q7648PT9MF.p8 # 密鑰-用於產生查詢訂閱API Token
      BundleID: com.fitopia.hub.dev
    Production:
      AppStoreServer: https://api.storekit-sandbox.itunes.apple.com
      Password: f7e5fb26e7cf4de3b8eff69950b6d747
      Issuer: 18f6ec13-f472-4dbc-8620-9a790c5d48e2
      KeyID: Q7648PT9MF
      KeyPath: ./config/SubscriptionKey_Q7648PT9MF.p8
      KeyName: SubscriptionKey_Q7648PT9MF.p8 # 密鑰-用於產生查詢訂閱API Token
      BundleID: com.fitopia.hub
IAB:
    TokenURL: https://oauth2.googleapis.com/token
    URL: https://androidpublisher.googleapis.com
    Scope: https://www.googleapis.com/auth/androidpublisher
    Expire: 30 # Minute
    Debug:
      JsonFilePath: ./config/fitness-iab-test.json
      KeyName: fitness-iab-test.json
      PackageName: com.henry.fitness.dev
    Release:
      JsonFilePath: ./config/fitopia-hub-console-9fec38062ede.json
      KeyName: fitopia-hub-console-9fec38062ede.json
      PackageName: com.fitopia.hub.dev
    Production:
      JsonFilePath: ./config/fitopia-hub-console-9fec38062ede.json
      KeyName: fitopia-hub-console-9fec38062ede.json
      PackageName: com.fitopia.hub
FCM:
    TokenURL: https://oauth2.googleapis.com/token
    URL: https://fcm.googleapis.com
    Scope: https://www.googleapis.com/auth/firebase.messaging
    Expire: 30 # Minute
    Debug:
      ProjectID: fitness-local
      KeyName: fcm-local-821466c48b.json
    Release:
      ProjectID: fitness-84141
      KeyName: fitness-84141-fcm-dev.json
    Production:
      ProjectID: fitopia-hub-console
      KeyName: fitopia-hub-console-fcm.json
FBLogin:
    Host: https://graph.facebook.com/
    Debug:
      AppID: 3268303936749363
      AppSecret: 9e81d8aea97dae4b4d47e2e58f1535e9
      DebugTokenURL: https://graph.facebook.com/debug_token
    Release:
      AppID: 3268303936749363
      AppSecret: 9e81d8aea97dae4b4d47e2e58f1535e9
      DebugTokenURL: https://graph.facebook.com/debug_token
    Production:
      AppID: 2179211948910676
      AppSecret: 28c553f706b72368a010852f82bc64e4
      DebugTokenURL: https://graph.facebook.com/debug_token
GoogleLogin:
    Iss: https://accounts.google.com
    DebugTokenURL: https://oauth2.googleapis.com/tokeninfo
    Debug:
      iOS:
        ClientID: 376527343165-tu7fr7epqgqc1c1mf2gbqppsn056alf8.apps.googleusercontent.com
      Android:
        ClientID: 376527343165-tu7fr7epqgqc1c1mf2gbqppsn056alf8.apps.googleusercontent.com
    Release:
      iOS:
        ClientID: 376527343165-dsk9555ua5ku7i3nf1g7jqf3olfqgh2q.apps.googleusercontent.com
      Android:
        ClientID: 657523385443-a1bqasg9cfug35hnp4dol31q55kror9l.apps.googleusercontent.com
    Production:
      iOS:
        ClientID: 657523385443-a3gqahkhou80evmcfbgeulc6srnd4ica.apps.googleusercontent.com
      Android:
        ClientID: 657523385443-j7g0sgj8qt8og93lbu1tfb81ga6ua8kn.apps.googleusercontent.com
AppleLogin:
    Debug:
      KeyName: AuthKey_ZN742MYSF4.p8 # Account/Certificates,IDs & Profiles/Keys
      TeamID: 4FN8272Q62 # Account/Membership
      KeyID: ZN742MYSF4 # Account/Certificates,IDs & Profiles/Keys
      BundleID: com.henry.LoginDemo
      DebugTokenURL: https://appleid.apple.com/auth/token
    Release:
      KeyName: AuthKey_278SQ8L8UK.p8
      TeamID: WDC8UY2P7F
      KeyID: 278SQ8L8UK
      BundleID: com.fitopia.hub
      DebugTokenURL: https://appleid.apple.com/auth/token
    Production:
      KeyName: AuthKey_278SQ8L8UK.p8
      TeamID: WDC8UY2P7F
      KeyID: 278SQ8L8UK
      BundleID: com.fitopia.hub
      DebugTokenURL: https://appleid.apple.com/auth/token
LineLogin:
    VerifyTokenURL: https://api.line.me/oauth2/v2.1/verify
    ProfileURL: https://api.line.me/v2/profile
    Debug:
      ClientID: 1657378278
    Release:
      ClientID: 1657326779
    Production:
      ClientID: 1656969705
Mail:
    SMTPHostName: smtp.gmail.com
    Debug:
      Port: 587
      Sender: toyokoyo199@gmail.com
      Password: qedvgrldwmeivfqw
    Release:
      Port: 587
      Sender: toyokoyo199@gmail.com
      Password: qedvgrldwmeivfqw
    Production:
      Port: 587
      Sender: toyokoyo199@gmail.com
      Password: qedvgrldwmeivfqw
OTP:
    Debug:
      Period: 300
    Release:
      Period: 300
    Production:
      Period: 300
Swagger:
    Debug:
      Protocol: http
      Host: 127.0.0.1:9090
      BasePath: /api
    Release:
      Protocol: https
      Host: www.fitopia-hub.life
      BasePath: /api
    Production:
      Protocol: https
      Host: www.fitopiahubapp.com
      BasePath: /api