Server:
    RunMode: debug
    HttpPort: 9090
    ReadTimeout: 60
    WriteTimeout: 60
App:
    Debug:
      Version: 1.9.2
    Release:
      Version: 1.9.2
Resource:
    RootPath: ./volumes/storage
Upload:
    UploadImageMaxSize: 5 #MB
    UploadAudioMaxSize: 10 #MB
    UploadVideoMaxSize: 60 #MB
    UploadImageAllowExt:
      - .jpg
      - .png
      - .jpeg
      - .JPG
      - .PNG
      - .JPEG
    UploadAudioAllowExt:
      - .mp3
    UploadVideoAllowExt:
      - .mp4
Log:
    FileName: fitness
    FileExt: log
    Debug:
      Path: ./volumes/log
      MaxAge: 60 # Minute
      RotationTime: 1 # Minute
    Release:
      Path: ./volumes/log
      MaxAge: 7 # Day
      RotationTime: 1 # Day
Database:
    DBType: mysql
    Debug:
      Host: 127.0.0.1:8889
      DBName: fitness
      UserName: henry
      Password: aaaa8027
    Release:
      Host: fitness-mysql-primary:3306 # k8s svc dns + k8s internal port
      DBName: fitness
      UserName: henry
      Password: aaaa8027
Redis:
    Debug:
      Host: 127.0.0.1:6379
      Password: ""
    Release:
      Host: fitness-redis-master:6379
      Password: aaaa8027
JWT:
    Secret: mi
    Issuer: fitness
    Expire: 3600 # Minute
IAP:
    Sandbox: https://sandbox.itunes.apple.com/verifyReceipt
    Product: https://buy.itunes.apple.com/verifyReceipt
    Debug:
      AppStoreServer: https://api.storekit-sandbox.itunes.apple.com
      Password: b3e50e11316943969754106ed24c6a3a
      Issuer: 69a6de92-1fe6-47e3-e053-5b8c7c11a4d1 # 發行者 (使用者與存取權限 -> App Store Connect API 頁面)
      KeyID: Q2N9VXCN4F # 密鑰id (使用者與存取權限 -> App 內購買項目)
      KeyPath: ./config/SubscriptionKey_Q2N9VXCN4F.p8
      BundleID: com.henry.PurchaseDemo
    Release:
      AppStoreServer: https://api.storekit-sandbox.itunes.apple.com
      Password: 0bd3a44a62f14ef9b79f1d16bf195835
      Issuer: 69a6de88-0ba0-47e3-e053-5b8c7c11a4d1
      KeyID: Y29YP83F2S
      KeyPath: ./config/SubscriptionKey_Y29YP83F2S.p8
      BundleID: com.anniestudio.Fitness
Swagger:
    Debug:
      Protocol: http
      Host: 127.0.0.1:9090
      BasePath: /api/v1
    Release:
      Protocol: https
      Host: www.fitness-app.tk
      BasePath: /api/v1