-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4ygHWNsqj1gu1fiw
Fyn6gDYE/Q7mdSX1UvG3WdDcgxmgCgYIKoZIzj0DAQehRANCAATKfG/ODt9C//Fw
OFvcasgfuJYF85qHy4yTsMFUuOrlf/vYQKman/bryk7j/O4D4ME5CEr4Sndk0QZy
UCWZ0E6A
-----END PRIVATE KEY-----